### ISSUE TITLE
[Suggestion] Support for list of excluded path/files

### ISSUE THREAD

**Issue by joyfulelement** [cheton/find-imports#2]
Hi @cheton : Is there a way to exclude certain directories/files specified under glob pattern? I believe it would be a good addition for this tool.

e.g. 

`const files = ['src/**/*.{js,jsx}']`
`const filesToExclude = ['src/**/*spec.js}']`
`findImports(files, filesToExclude)`

**Comment by cheton** [comment]
Good suggestion. I will change the code to follow the usage of <b>gulp.src</b> API. For example:

``` jsx
const files = [
    'src/**/*.{js,jsx}',
    // Exclude *.spec files
    '!src/**/*spec.js'
];
gulp.src(files);
```

Ref. https://github.com/gulpjs/glob-stream/blob/master/index.js#L101
