### ISSUE TITLE
Is it possible to support scss files?

### ISSUE THREAD

**Issue by cjcheshire** [cheton/find-imports#4]
Hey, this is an amazing library.  I'm trying to find all uses of a particular library. I noticed in your demo you suggested it found a css file. I'm am trying to find imports in scss files.

```
const files = [
  'src/**/*.{js,jsx,scss}',
  '!src/lib/*.*',
];

const results = findImports(files, {
  absoluteImports: true,
  relativeImports: true,
  flatten: true,
});
```

Sadly this outputs ```Error in `undefined`: SyntaxError: /Users/ccheshire/Development/work/app-qa/src/css/_action-buttons.scss: Unexpected token (1:0)```

The action-buttons file itself only includes a few css classes.

Is this because the scss file isn't javascript and therefore the syntax isn't valid?

**Comment by cheton** [comment]
This library is purposed to find all import statements in JavaScript files, it cannot parse `.css`, `.less`, `.scss`, or `.styl` files. In your case, you need to use [node-glob](https://github.com/isaacs/node-glob) combing with regular expressions to parse `@import` statements in .scss files, like so:

```js
var glob = require('glob');

glob('**/*.scss', { /* options */ }, function(err, files) {
    // files is an array of filenames.
    files.forEach(function(file) {
        // Use regular expression to match @import statements
        //     :  :   :
    });
});
```

Check out code below for my regular expressions:
https://github.com/cheton/browserify-css/blob/master/css-transform.js#L218-L239

**Comment by cjcheshire** [comment]
Thank you, that’s most helpful. Yesterday I played with something similar to your suggestion. 

Thanks for the suggestion and the rapid response :)

I’ll close this now.
