### ISSUE TITLE
recursive?

### ISSUE THREAD

**Issue by isaacs** [cheton/find-imports#7]
I need to get all the local imports from a given file recursively (so that I'll know when I have to re-run a test if a relevant source file changes).

Can this module do that already?  If not, it could just be a separate module that depends on this one.

**Comment by cheton** [comment]
@isaacs Yes, it can get all local imports recursively using the `relativeImports` flag, and generate a flat output according to your needs. Negated glob pattern is also supported to ignore certain files.

https://github.com/cheton/find-imports/blob/master/test/index.js

If you want to detect file changes, you can combine with the [watch](https://github.com/mikeal/watch) module to specify directories you want to watch.

**Comment by ackvf** [comment]
Does recursive in this context mean all imports from a given entry point while also traversing the imported files themselves? I also wanted to ask, but seems like I don't need to create new question.

So, will it collect all imports if I give it my app's entry point `src/App.tsx` or does it take its files just from the glob?

**Comment by ackvf** [comment]
@isaacs would you mind answering as well since you closed it now?

**Comment by isaacs** [comment]
Yes, "recursive" in my usage above does mean "all imports from a given entry point while also traversing the imported files themselves".

I closed the issue because I no longer have this need.  Tap is using code coverage reporting to determine which files are loaded by which tests, which is a simpler anad more reliable approach for my use case.
